### ISSUE TITLE
No loading of the map, no errors

### ISSUE THREAD

**Issue by francis0509** [thebuildcraft/RemotePlayerWaypointsForXaero#28]
So, i am playing on a bungeecord server and there are 2 servers: Nations and Towny. I don't play Towny so that isn't a problem but in the map link there are "map.ccnetmc.com/nationsmap" and "map.ccnetmc/townymap". I put "map.ccnetmc.com/nationsmap" and it says no errors in chat, but it doesn't load anything into to Xaero's World Map.

Logs when i put config:

`[16:05:54] [Timer-1/INFO]:
mapConfig: <html><head><title>301 Moved Permanently</title></head><body><center><h1>301 Moved Permanently</h1></center><hr><center>cloudflare</center></body></html>
[16:05:54] [Timer-1/INFO]:
mapConfig: var config = { url : { configuration: 'standalone/dynmap_config.json?_={timestamp}', update: 'standalone/dynmap_{world}.json?_={timestamp}', sendmessage: 'standalone/sendmessage.php', login: 'standalone/login.php', register: 'standalone/register.php', tiles: 'tiles/', markers: 'tiles/' }};
[16:05:54] [Timer-1/INFO]:
configuration link: https://map.ccnetmc.com/nationsmap/standalone/dynmap_config.json
[16:05:54] [Timer-1/INFO]:
firstWorldName: world
[16:05:54] [Timer-1/INFO]:
updateStringTemplate: /standalone/dynmap_{world}.json?_=1
[16:05:54] [Timer-1/INFO]:
url: https://map.ccnetmc.com/nationsmap/standalone/dynmap_world.json?_=1
[16:05:54] [Timer-1/INFO]:
new link: https://map.ccnetmc.com/nationsmap/standalone/dynmap_world.json?_=1`

Config: 
`{
	"enabled": true,
	"updateDelay": 2000,
	"serverEntries": [
		{
			"maptype": "Dynmap",
			"ip": "play.ccnetmc.com",
			"link": "map.ccnetmc.com/nationsmap/"
		}
	],
	"defaultY": 64,
	"minimapWaypointsRenderBelow": "WHEN_PLAYER_LIST_SHOWN",
	"enablePlayerWaypoints": true,
	"enablePlayerIcons": true,
	"timeUntilAfk": 120,
	"showAfkTimeInTabList": true,
	"unknownAfkStateColor": 6316128,
	"AfkColor": 16733440,
	"playerWaypointColor": "Black",
	"enableMarkerWaypoints": true,
	"markerWaypointColor": "Gray",
	"ignoredServers": [],
	"ignoreMarkerMessage": false,
	"debugMode": false,
	"minDistance": 0,
	"maxDistance": 100000,
	"maxIconDistance": 100000,
	"minDistanceMarker": 0,
	"maxDistanceMarker": 100000
}`

**Comment by francis0509** [comment]
Said a error 20 minutes later
`[16:20:00] [Timer-1/INFO]: [CHAT] [Remote Player Waypoints For Xaero's Map]: Failed to make online map request (for marker waypoints). Please check your config (probably your link...) or report a bug.
[16:20:00] [Timer-1/INFO]: [STDERR]: java.io.FileNotFoundException: https://map.ccnetmc.com/nationsmap/tiles/_markers_/marker_-some-other-bogus-world-.json
[16:20:00] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:20:00] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:20:00] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[16:20:00] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeTextHttpRequest(HTTP.java:81)
[16:20:00] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeJSONHTTPRequest(HTTP.java:55)
[16:20:00] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.connections.DynmapConnection.getWaypointPositions(DynmapConnection.java:213)
[16:20:00] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.runUpdate(UpdateTask.java:230)
[16:20:00] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.run(UpdateTask.java:94)
[16:20:00] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[16:20:00] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)
[16:20:01] [Render thread/INFO]: [CHAT] [AS|Calgary] [Supporter] ~mcaxuburger » free my boy
[16:20:02] [Timer-1/INFO]: [STDERR]: java.io.FileNotFoundException: https://map.ccnetmc.com/nationsmap/tiles/_markers_/marker_-some-other-bogus-world-.json
[16:20:02] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:20:02] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:20:02] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[16:20:02] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeTextHttpRequest(HTTP.java:81)
[16:20:02] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeJSONHTTPRequest(HTTP.java:55)
[16:20:02] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.connections.DynmapConnection.getWaypointPositions(DynmapConnection.java:213)
[16:20:02] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.runUpdate(UpdateTask.java:230)
[16:20:02] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.run(UpdateTask.java:94)
[16:20:02] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[16:20:02] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)
[16:20:04] [Timer-1/INFO]: [STDERR]: java.io.FileNotFoundException: https://map.ccnetmc.com/nationsmap/tiles/_markers_/marker_-some-other-bogus-world-.json
[16:20:04] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:20:04] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:20:04] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[16:20:04] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeTextHttpRequest(HTTP.java:81)
[16:20:04] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeJSONHTTPRequest(HTTP.java:55)
[16:20:04] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.connections.DynmapConnection.getWaypointPositions(DynmapConnection.java:213)
[16:20:04] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.runUpdate(UpdateTask.java:230)
[16:20:04] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.run(UpdateTask.java:94)
[16:20:04] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[16:20:04] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)
[16:20:06] [Timer-1/INFO]: [STDERR]: java.io.FileNotFoundException: https://map.ccnetmc.com/nationsmap/tiles/_markers_/marker_-some-other-bogus-world-.json
[16:20:06] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:20:06] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:20:06] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[16:20:06] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeTextHttpRequest(HTTP.java:81)
[16:20:06] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeJSONHTTPRequest(HTTP.java:55)
[16:20:06] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.connections.DynmapConnection.getWaypointPositions(DynmapConnection.java:213)
[16:20:06] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.runUpdate(UpdateTask.java:230)
[16:20:06] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.run(UpdateTask.java:94)
[16:20:06] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[16:20:06] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)
[16:20:06] [Render thread/INFO]: [CHAT] [DOC|Kibou] [Excelsior] ~PandaMagician » he said uh
[16:20:08] [Timer-1/INFO]: [STDERR]: java.io.FileNotFoundException: https://map.ccnetmc.com/nationsmap/tiles/_markers_/marker_-some-other-bogus-world-.json
[16:20:08] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:20:08] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:20:08] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[16:20:08] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeTextHttpRequest(HTTP.java:81)
[16:20:08] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeJSONHTTPRequest(HTTP.java:55)
[16:20:08] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.connections.DynmapConnection.getWaypointPositions(DynmapConnection.java:213)
[16:20:08] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.runUpdate(UpdateTask.java:230)
[16:20:08] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.run(UpdateTask.java:94)
[16:20:08] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[16:20:08] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)
[16:20:10] [Timer-1/INFO]: [STDERR]: java.io.FileNotFoundException: https://map.ccnetmc.com/nationsmap/tiles/_markers_/marker_-some-other-bogus-world-.json
[16:20:10] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:20:10] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:20:10] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[16:20:10] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeTextHttpRequest(HTTP.java:81)
[16:20:10] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeJSONHTTPRequest(HTTP.java:55)
[16:20:10] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.connections.DynmapConnection.getWaypointPositions(DynmapConnection.java:213)
[16:20:10] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.runUpdate(UpdateTask.java:230)
[16:20:10] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.run(UpdateTask.java:94)
[16:20:10] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[16:20:10] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)
[16:20:12] [Timer-1/INFO]: [STDERR]: java.io.FileNotFoundException: https://map.ccnetmc.com/nationsmap/tiles/_markers_/marker_-some-other-bogus-world-.json
[16:20:12] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:20:12] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:20:12] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[16:20:12] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeTextHttpRequest(HTTP.java:81)
[16:20:12] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeJSONHTTPRequest(HTTP.java:55)
[16:20:12] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.connections.DynmapConnection.getWaypointPositions(DynmapConnection.java:213)
[16:20:12] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.runUpdate(UpdateTask.java:230)
[16:20:12] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.run(UpdateTask.java:94)
[16:20:12] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[16:20:12] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)
[16:20:13] [Render thread/INFO]: [CHAT] [DOC|Kibou] [Excelsior] ~PandaMagician » to someone to unalive themselfs
[16:20:14] [Timer-1/INFO]: [STDERR]: java.io.FileNotFoundException: https://map.ccnetmc.com/nationsmap/tiles/_markers_/marker_-some-other-bogus-world-.json
[16:20:14] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:20:14] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:20:14] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[16:20:14] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeTextHttpRequest(HTTP.java:81)
[16:20:14] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeJSONHTTPRequest(HTTP.java:55)
[16:20:14] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.connections.DynmapConnection.getWaypointPositions(DynmapConnection.java:213)
[16:20:14] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.runUpdate(UpdateTask.java:230)
[16:20:14] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.run(UpdateTask.java:94)
[16:20:14] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[16:20:14] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)
[16:20:16] [Timer-1/INFO]: [STDERR]: java.io.FileNotFoundException: https://map.ccnetmc.com/nationsmap/tiles/_markers_/marker_-some-other-bogus-world-.json
[16:20:16] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:20:16] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:20:16] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[16:20:16] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeTextHttpRequest(HTTP.java:81)
[16:20:16] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeJSONHTTPRequest(HTTP.java:55)
[16:20:16] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.connections.DynmapConnection.getWaypointPositions(DynmapConnection.java:213)
[16:20:16] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.runUpdate(UpdateTask.java:230)
[16:20:16] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.run(UpdateTask.java:94)
[16:20:16] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[16:20:16] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)
[16:20:18] [Render thread/INFO]: [CHAT] [AS|Calgary] [Supporter] ~mcaxuburger » erm
[16:20:18] [Timer-1/INFO]: [STDERR]: java.io.FileNotFoundException: https://map.ccnetmc.com/nationsmap/tiles/_markers_/marker_-some-other-bogus-world-.json
[16:20:18] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[16:20:18] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[16:20:18] [Timer-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[16:20:18] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeTextHttpRequest(HTTP.java:81)
[16:20:18] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.HTTP.makeJSONHTTPRequest(HTTP.java:55)
[16:20:18] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.connections.DynmapConnection.getWaypointPositions(DynmapConnection.java:213)
[16:20:18] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.runUpdate(UpdateTask.java:230)
[16:20:18] [Timer-1/INFO]: [STDERR]: 	at de.the_build_craft.remote_player_waypoints_for_xaero.common.UpdateTask.run(UpdateTask.java:94)
[16:20:18] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
[16:20:18] [Timer-1/INFO]: [STDERR]: 	at java.base/java.util.TimerThread.run(Unknown Source)`

**Comment by thebuildcraft** [comment]
Are you switching dimensions or servers when the error happens? Also, please try to disable the marker waypoints in the config.

**Comment by francis0509** [comment]
No i were not switching servers or dimensions. I tried disabling the marker waypoints and it does not load anything.

**Comment by thebuildcraft** [comment]
OK, when I switch my username to yours and join my localhost offline mode server with your map link, it works perfectly fine. Maybe try to disable the mod while being on the child server and then re-enable it again.

**Comment by thebuildcraft** [comment]
If that doesn't help, try this:
/remote_player_waypoints_for_xaero set_current_dimension_overwrite true
/remote_player_waypoints_for_xaero set_current_dimension world  <--- change to correct world name if you go to a world other than the overworld

**Comment by francis0509** [comment]
I tried the mod on a fresh modpack it loads the markers but it doesn't load the map

**Comment by thebuildcraft** [comment]
So it displays the players as waypoints and icons, and the map markers as waypoints?
Then everything is working! This mod doesn't sync the online map data, only the player and marker positions.

**Comment by thebuildcraft** [comment]
No problem ... :)
